webpt:
  build: ./webdata
  ports:
    - "8080"

kafka:
  build: ./kafka
  ports:
    - "9082"
    - "2282"
  volumes:
    - kafka/config:/opt/kafkaconfig

redis:
  build: ./redis
  ports:
   - "6390"
  volumes:
   - redis/conf:/opt/redisconf/
